export const ADD_TO_WEIGHT_COMPARISON = "ADD_TO_WEIGHT_COMPARISON";
export const ADD_TO_VOLUME_COMPARISON = "ADD_TO_VOLUME_COMPARISON";
export const ADD_TO_COUNT_COMPARISON = "ADD_TO_COUNT_COMPARISON";
